apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-poam
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ycbz-tenant/rhtap-demo-app/hacbs-test-project-poam@sha256:8cfe7da7d2896531bd8f41ffcc0a33ffb9ab10b1dd3fff0ce6e03214b4ad8db3
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
